### ISSUE TITLE
How to have an empty line in an output HTML?

### ISSUE THREAD

**Issue by evgeniy-vashchuk** [gulp-community/gulp-pug#191] opened 2018-08-26 12:58 UTC
I want to see empty lines in my output HTML, but PUG removes all of it:

![e03544252a](https://user-images.githubusercontent.com/24987866/44628434-5c88aa80-a948-11e8-82c6-dd263d40c433.png)

What I want:

![c87a53db49](https://user-images.githubusercontent.com/24987866/44628466-c903a980-a948-11e8-98fe-8987726a7af0.png)

How can I change this? Pug have any options for this?

**Comment by demurgos** [comment] 2018-08-26 15:30
Your question is very specific and related to pug-the-language, not the Gulp plugin. You should ask it on StackOverflow or the [Pug repo](https://github.com/pugjs/pug).

I don't have the answer to your question, but you may look at HTML literals or something like this. I remember using the pipe `|` operator to emit some content. I'm closing this issue since it's not a bug with the plugin.

**Closed as completed by demurgos** 2018-08-26 15:30 UTC
Labels: question
